name: My Workflow
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: github-actions

jobs:
  examplejob:
    runs-on: ubuntu-latest
    steps:
      - run : echo "checkout repo"
      - name : checkout Repo
        uses: actions/checkout@v2
      - run: printenv
      - run: echo "this is the env ${{env.PROJECT_NAME}} AND {{env.PROJECT_NAME}}"